package com.example.dogshoppe;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.ArrayList;

///---------- This is the data provider class to read from CSV and generate the data -------------
public class Categories {
    InputStream filepath;


 // Descriptions hard coded for each item in each category
 // hardcoding item descriptions for each category because we found it runs over many lines on
 // the csv, so the descriptions gets cut off.
     String[] alldescr ={"Woof Freeze Dried Dog Bites from The New Zealand Natural Pet Food Co are made using only the highest quality ingredients aimed at nourishing your pet's health. We combine the nutrition and taste of fresh, raw food and put it through a gentle freeze drying process which protects all the natural enzymes and nutrients, so none of the wholesome goodness is cooked out. It's simply delicious, raw food that your dog will love!"
         , "After thousands of years of delectable squid slipping from their paws, dogs can now enjoy this high value treato thanks to the invention of freeze drying and the tenacity of Gourmate Pet Treat Co. These restaurant quality Wild Caught Calamari rings and things are a unique au natural high protein pet treat of only 8% fat - perfect for small and tall dogs alike."
         , "Wild goat is an excellent choice when searching for a healthy red meat for your pet. Goat meat is high in iron and protein, with low levels of saturated fat, making it a leaner and healthier option. It is rich in Vitamin B and potassium which helps maintain a healthy weight and a strong heart. Goat is also a natural source of Omega-3 fatty acids and other essential minerals which support healthy skin and coat."
         , "Gourmate’s restaurant quality, grass fed and free range Angus Beef Liver is a chunky and meaty nutrient boost that’s tail-waggingly good and good for them. High-tech freeze drying preserves the texture, flavour and nutrition of rich Angus Beef Liver to catch the nose of even the fussiest dog. Pet treats are intended for supplement feeding only. We recommend 1 big or 2 small chunks per day."
         , "For small breed puppies (adult weight up to 10 kg) - Up to 10 months old. Royal Canin Premium Mini Breed Puppy food helps maintain ideal body weight and healthy bones and joints. Meets the energy needs of small breed puppies during the growth period, and satisfies fussy appetites."
         , "EUKANUBA Adult All Breed provides optimal nutrition for adult all breed dogs (11-24kg.) The kibbles are medium size and contain high quality ingredients such as poultry protein as our No 1 ingredient, fat, carbohydrates, fibres and important vitamins and minerals for the health and wellbeing of your adult all breed dog."
         , "Ocean fish and salmon as the main ingredients provide a novel protein for dogs with allergies or intolerances. Potato for energy, digestion and sensitive stomachs. Emu oil for skin, coat and joint health. Suitable for all breeds of adult dogs. 100% complete and balanced."
         , "Lamb for strong muscles, healthy bones and vitality. Blueberries and cranberries for immunity and natural defense. Emu oil for skin, coat and joint health. Suitable for all breeds of adult dogs. 100% complete and balanced."
         , "Big dogs need lots of love, and Hill's Science Diet Large Breed Puppy dry food is specially made with a delicious chicken flavour and an optimal level of calcium for controlled bone growth: a unique developmental need of large breed puppies. This dog food made with natural ingredients uses DHA from fish oil to support your large dog's eye development and brain function."
         , "A delicious complement to the superior nutrition of Hill's Science Det dry food. Ingredients: Water, Beef, Liver, Brown rice, Wheat flour, Carrots, Rice starch-modified, Potato starch, Dried beet pulp, Pork plasma, Potatoes, Chicken liver flavour, Vitamins & minerals."
         , "You want to give your puppy the best start on life possible, and Hill's Science Diet Puppy Savory Stew with Chicken & Vegetables is a delicious way to provide precisely balanced nutrition that is important to the overall health and wellbeing of your growing puppy. Easy-to-digest ingredients make stool pickup easy. Made with real chicken and wholesome grains, this puppy food made with natural ingredients provides balanced minerals to promote strong bones and healthy teeth in your young dog."
         , "Juicy and succulent, lamb is a tasty source of protein and iron, essential for strong bones and muscles. Lamb also has zinc and vitamin B12 which promotes cardiovascular health, aid metabolism and boost vitality. Formulated to be used as a complete meal or added to dry food to supplement your dog's meal. Suitable for all breeds of adult dogs. Tailored for dogs who have allergies to grains that can sometimes be included in other dog foods."
         ,"Doggo’s playtime will be abuzz with excitement when they dig into the Zippy Burrow Bees in Honeypot! It’s the perfect interactive toy for keeping your dog busily engaged in hide-and-seek play that prevents boredom and promotes mental stimulation! This interactive hide-and-seek toy comes with 1 honey pot and 3 small squeaky bees."
         ,"Make popcorn the star of your pupper’s playtime with the Zippy Burrow Popcorn Bucket! Simply hide the popcorn balls in the bucket, sit back, relax and enjoy the show! It’s the perfect interactive toy for keeping your dog busy and engaged through hide-and-seek play that prevents boredom and promotes mental stimulation! This interactive hide-and-seek toy comes with 1 popcorn bucket and 3 small squeaky popcorn balls."
         ,"NomNomz® are your favorite foods, now in plush form for your pups! Feed your dog's inner foodie with these \"delicious\" yummy treats, one bite and they'll be in doggie heaven."
         ,"Rawr! Donny the Dinosaur is the durable dog toy of your pup’s prehistoric dreams! Donny includes a loud Grunter and features plaid accents, embroidered detailing and colorful cross-stitched fabric. Constructed using ZippyPaws’ exclusive Z-Stitch® webbing and multi-layered fabric, Donny is perfect for cuddling, tossing, fetching – and chewing! However Donny is not in-destructible tho!"
         ,"NomNomz® are your favourite foods, now in plush form for your pups! Feed your dog's inner foodie with these \"delicious\" yummy treats, one sip and they'll be in doggie heaven."
         ,"Where’s Dodo?! Dodo the Dodo Bird is flightless and fearless – the perfect combo for playtime with your pupper! Dodo includes a loud Grunter and features plaid accents, embroidered detailing and colorful cross-stitched fabric. Constructed using ZippyPaws’ exclusive Z-Stitch® webbing and multi-layered fabric, Dodo is perfect for cuddling, tossing, fetching – and chewing!"
         ,"Dogs of all ages and sizes will love to get a bite of the Bolt Bite chew toy. With a reinforced centre, two elbows for engaging paw-play, and open ends for hiding treats. Whether you have a strong-jawed dog or a teething puppy, the Bolt Bite is made for all shapes, sizes and ages."
         ,"The Twist Toss is the ultimate fetch toy for dogs. It bounces unpredictably for active play and holds treats. Head to the park and have a ball or add your favourite spread and freeze the Twist Toss for a longer lasting snack."
         ,"The Triangle Tug boasts two shapes, two textures, and is perfect for tug-of-war. If you’re in a multi-dog household or if you’re at the other end of your pups tug-match, the Triangle Tug is built for you."
         ,"Keep meal time and treats exciting with the Snack Snake! Fill the opening with food or treats and let them go for gold."
         ,"This award-winning treat toy is safe for every pet as it's durable and designed to be filled with a dog's favourite kibble, wet food or treats! Toppl's soft, rounded inner 'teeth' contain a contoured cavity to hold treats in place until your dog nudges them out."
         ,"NomNomz® are your favorite foods, now in plush form for your pups! Feed your dog's inner foodie with these \"delicious\" yummy treats, one bite and they'll be in doggie heaven."
         ,"Phone rings and you’re holding your dog and a coffee? No problem. One CLIC ties your dog to a railing and so you can get to your phone. Paying for a coffee? One simple CLIC frees your hands for any occasion and errands. Stylish and innovative design for everyday use. Beige colour rope with tan leather trim design. Perfect for any dog size up to 40kg. Tether a dog with one hand in a single motion. Option to not use a traditional collar - thanks to Leader System.\n" + "Product Measurements: 1.4m maximum in length, 8mm thickness: 8kg maximum dog weight, 11mm thickness: 40kg maximum dog weight"
         ,"If you and your furry friend like to traverse off-road, then this is the multi-purpose leash for you! The durable and flexible soft coated webbing material makes this lead waterproof, stain-proof and stink-proof, so it’s super easy to keep clean. This versatile leash allows you to go completely hands-free with cross-body functionality. You can also conveniently adjust its length from short (100cm) to long (180cm), depending on the terrain or your doggo. The adjustable length means you can even tether your doggo to a tree while you’re out exploring together. Two width to choose from 2cm (Small) or 2.5cm (Large)."
         ,"If you and your furry friend like to traverse off-road, then this is the multi-purpose leash for you! The durable and flexible soft coated webbing material makes this lead waterproof, stain-proof and stink-proof, so it’s super easy to keep clean. This versatile leash allows you to go completely hands-free with cross-body functionality. You can also conveniently adjust its length from short (100cm) to long (180cm), depending on the terrain or your doggo. The adjustable length means you can even tether your doggo to a tree while you’re out exploring together. Two width to choose from 2cm (Small) or 2.5cm (Large)."
         ,"This simple leash is a perfect multi-tasker for everyday use! Use it in different ways with adjustable lengths. Strong and easy to use buckle, make everyday dog walk activities enjoyable!"
         ,"This simple leash is a perfect multi-tasker for everyday use! Use it in different ways with adjustable lengths. Strong and easy to use buckle, make everyday dog walk activities enjoyable!"
         ,"This simple leash is a perfect multi-tasker for everyday use! Use it in different ways with adjustable lengths. Strong and easy to use buckle, make everyday dog walk activities enjoyable!"
         ,"Our all weather collars are a durable alternative to leather. They are made with sustainable recycled canvas and solid brass, for pups who love to explore. Made by hand in Australia. Canvas exterior - made from recycled plastic bottles. Synthetic core for strength - made from recycled plastic bottles. Environmental friendly. Cruelty-free. Sewn and hand riveted. Solid brass hardware."
         ,"Looking for something that's back-to-school-chic? Tartan is a classic style so we've made these from a left over roll of school uniform twill. The colours look smart with brass hardware for a slightly formal look. Is 'dapper' your middle name? Then this is for you. Environmental friendly. Made by hand in Australia. Cotton exterior for beauty. Synthetic core for strength. Sewn and hand riveted. 100% solid brass hardware."
         ,"Each Le Classic Dog Collar is a chic and ultra-comfortable essential for the on-the-go dog. Every vibrant collar is made of premium-quality vegan materials + faux leather. Le Classic Collar comes in four sizes for the perfect fit and was created to suit dogs of all temperaments. Collars features a matte black buckle + triangle ring, antique gold eyelets and our custom rose emblem. We truly believe that luxury lies in the delicate details. Each Le Classic Dog Collar and its striking pattern can be paired with a matching Le Classic Leash to complete the signature look."
         ,"No more rashes under your armpits! Hooray to the patented smart design of X-Harness, make running around in parks or beaches extra fun! Made from strong acrylic yarn with the feel of cotton's soft texture. One continuous strap. Easy to put on and remove without pulling your dog’s legs through the harness."
         ,"No more rashes under your armpits! Hooray to the patented smart design of X-Harness, make running around in parks or beaches extra fun! Made from strong acrylic yarn with the feel of cotton's soft texture. One continuous strap. Easy to put on and remove without pulling your dog’s legs through the harness."
         ,"No more rashes under your armpits! Hooray to the patented smart design of X-Harness, make running around in parks or beaches extra fun! Made from strong acrylic yarn with the feel of cotton's soft texture. One continuous strap. Easy to put on and remove without pulling your dog’s legs through the harness."
         ,"Super handy Andis Blade Cleaning Brush with nice long bristles. Designed specifically for cleaning blades and clippers. Measures 14cm total length. The bristle area of the brush measures 6cm and the bristles themselves are a generous 1.5cm long for really getting out stuck fur. Great for brushing out fur from between blade teeth and between blades, cleaning clipper parts like the blade latch and air filter - a great little all-rounder!"
         , "Natural Wooden Bamboo Bristle Brush Single Sided. Medium/Firm Bristles. Bristles Length 2 cm. Total Brush Length 22 x 6 cm. Ideal time saver."
         , "Very sturdy rubber brush. Can be used on Dogs or Horses. Treat your Dog  or Horse to a safe gentle massage. Great for massaging in shampoo. Lots of soft rubber pins for a gentle massage. Easy to hold fits nicely in your hand with good grip. Weight: 0.2 kg."
         , "High quality steel. These are a great scissor for the entry level Groomer  up to the  intermediate level Groomer. Thinners are 6.5″. Straight Scissor & Curved Scissor are 7″. Available in Electric Blue only. This Triple Pack comes with its own pouch for convenience & safety."
         , "The Black Pearl is a shear designed to revolutionize the industry. Very high quality at low cost. Designed with our ergonomic shank handle design, this shear has power, but can handle the smallest details with finesse. Weight: 1 kg."
         , "Tooth to Tooth measures 3.5cm. Stripping tools are ideal for removing loose hair and thin out undercoats quickly and easily. Special designed curved blades with rounded ends for safety. Comfortable wooden handle is easy to grip, reduces  hand fatigue. Strips coats cleanly and effectively, leaving coats and skin healthy. For best result, and to avoid removing excessive top coats, use only in the direction of hair growth. 8 Blade, 10 Blade, and 12 Blade for prep work and thinning. 13 Blade, 16 Blade, and 20 Blade for heavy coats. 26 Blade, 27 Blade, and 32 Blade for finishing or on thick, shaggy coats. Weight: 1 kg."
         , "Unique de matting tool has double sided stainless steel blades. Fine on one side and Coarse on other to remove mats, tangles and knots easily without losing coat length. 9 Blades on the Coarse side. 17 Blades on the Fine side. Easy grip rubber handle. Weight: 0.1 kg."
         , "Running Time of  240 mins – 4 hours on low speed, 180 min at high speed. Re-Charge in ONLY 60 mins. Convenient Battery Level Indicator for ease of use. RED LIGHT -FLAT CHARGING. ORANGE LIGHT TRICKLE CHARGING. GREEN FULLY CHARGED. PLEASE NOTE:BATTERY MUST BE COLD BEFORE PLACING ON THE CHARGER UNIT THIS WILL PROLONG THE LIFE OF THE BATTERY. Lightweight & Economical Design to fit perfectly in the hand. Ideal for all Dog Types & Full Body Clips on Horses. Weight: 5 kg."
         , "Professional Grooming Clipper. Ergonomically designed  – light weight at 350gm. Slim styling – Slip resistant grip on lower case for secure hold and improved handling. Two powerful speeds  3000 and 3700 rpm. Brushless motor. 4.2 metre long cord. Energy saving switch mode power supply with low voltage, greater safety for user and animal. Fast cutting size 10 blade with cutting length of 1.8mm. Bottle of Blade Oil."
         , "Excellent Small Clipper for Full Clips on Cats and Dogs. Bridle Paths on Horses. Touch up for Freeze Branding. This Clipper has a quiet and powerful 35w permanent magnet motor. Handpiece and battery weigh only 440gms. Weight: 2 kg."
         , "Great for Cats and Dogs. Ideal for brush-outs and mat removal. Leaves coats smooth looking. Head has angled pins are great for detangling with the least risk of brush burn. Ideal for bath prepping or undercoat removal. Brush Head measures  6cm x 4cm. Easy grip rubber handle. Weight: 0.1 kg."
         , "Removes mats, dead and shedding hair with great results with no extra effort. Brush features a super strong soft plastic grip handle Soft foam-cushioned pad and curved head. Removes shedding hair without damaging topcoat Soft foam-cushioned pad and curved head. Soft foam-cushioned pad and curved head. Provides a beautiful and long lasting well groomed finish. Easy grip rubber handle for ease of use. Large Size measures 12cm x 7cm. Weight: 0.1 kg"
     };


     String[] foodDescr = {"Woof Freeze Dried Dog Bites from The New Zealand Natural Pet Food Co are made using only the highest quality ingredients aimed at nourishing your pet's health. We combine the nutrition and taste of fresh, raw food and put it through a gentle freeze drying process which protects all the natural enzymes and nutrients, so none of the wholesome goodness is cooked out. It's simply delicious, raw food that your dog will love!"
            , "After thousands of years of delectable squid slipping from their paws, dogs can now enjoy this high value treato thanks to the invention of freeze drying and the tenacity of Gourmate Pet Treat Co. These restaurant quality Wild Caught Calamari rings and things are a unique au natural high protein pet treat of only 8% fat - perfect for small and tall dogs alike."
            , "Wild goat is an excellent choice when searching for a healthy red meat for your pet. Goat meat is high in iron and protein, with low levels of saturated fat, making it a leaner and healthier option. It is rich in Vitamin B and potassium which helps maintain a healthy weight and a strong heart. Goat is also a natural source of Omega-3 fatty acids and other essential minerals which support healthy skin and coat."
            , "Gourmate’s restaurant quality, grass fed and free range Angus Beef Liver is a chunky and meaty nutrient boost that’s tail-waggingly good and good for them. High-tech freeze drying preserves the texture, flavour and nutrition of rich Angus Beef Liver to catch the nose of even the fussiest dog. Pet treats are intended for supplement feeding only. We recommend 1 big or 2 small chunks per day."
            , "For small breed puppies (adult weight up to 10 kg) - Up to 10 months old. Royal Canin Premium Mini Breed Puppy food helps maintain ideal body weight and healthy bones and joints. Meets the energy needs of small breed puppies during the growth period, and satisfies fussy appetites."
            , "EUKANUBA Adult All Breed provides optimal nutrition for adult all breed dogs (11-24kg.) The kibbles are medium size and contain high quality ingredients such as poultry protein as our No 1 ingredient, fat, carbohydrates, fibres and important vitamins and minerals for the health and wellbeing of your adult all breed dog."
            , "Ocean fish and salmon as the main ingredients provide a novel protein for dogs with allergies or intolerances. Potato for energy, digestion and sensitive stomachs. Emu oil for skin, coat and joint health. Suitable for all breeds of adult dogs. 100% complete and balanced."
            , "Lamb for strong muscles, healthy bones and vitality. Blueberries and cranberries for immunity and natural defense. Emu oil for skin, coat and joint health. Suitable for all breeds of adult dogs. 100% complete and balanced."
            , "Big dogs need lots of love, and Hill's Science Diet Large Breed Puppy dry food is specially made with a delicious chicken flavour and an optimal level of calcium for controlled bone growth: a unique developmental need of large breed puppies. This dog food made with natural ingredients uses DHA from fish oil to support your large dog's eye development and brain function."
            , "A delicious complement to the superior nutrition of Hill's Science Det dry food. Ingredients: Water, Beef, Liver, Brown rice, Wheat flour, Carrots, Rice starch-modified, Potato starch, Dried beet pulp, Pork plasma, Potatoes, Chicken liver flavour, Vitamins & minerals."
            , "You want to give your puppy the best start on life possible, and Hill's Science Diet Puppy Savory Stew with Chicken & Vegetables is a delicious way to provide precisely balanced nutrition that is important to the overall health and wellbeing of your growing puppy. Easy-to-digest ingredients make stool pickup easy. Made with real chicken and wholesome grains, this puppy food made with natural ingredients provides balanced minerals to promote strong bones and healthy teeth in your young dog."
            , "Juicy and succulent, lamb is a tasty source of protein and iron, essential for strong bones and muscles. Lamb also has zinc and vitamin B12 which promotes cardiovascular health, aid metabolism and boost vitality. Formulated to be used as a complete meal or added to dry food to supplement your dog's meal. Suitable for all breeds of adult dogs. Tailored for dogs who have allergies to grains that can sometimes be included in other dog foods."
    };

     String[] toysDescr = {"Doggo’s playtime will be abuzz with excitement when they dig into the Zippy Burrow Bees in Honeypot! It’s the perfect interactive toy for keeping your dog busily engaged in hide-and-seek play that prevents boredom and promotes mental stimulation! This interactive hide-and-seek toy comes with 1 honey pot and 3 small squeaky bees."
            ,"Make popcorn the star of your pupper’s playtime with the Zippy Burrow Popcorn Bucket! Simply hide the popcorn balls in the bucket, sit back, relax and enjoy the show! It’s the perfect interactive toy for keeping your dog busy and engaged through hide-and-seek play that prevents boredom and promotes mental stimulation! This interactive hide-and-seek toy comes with 1 popcorn bucket and 3 small squeaky popcorn balls."
            ,"NomNomz® are your favorite foods, now in plush form for your pups! Feed your dog's inner foodie with these \"delicious\" yummy treats, one bite and they'll be in doggie heaven."
            ,"Rawr! Donny the Dinosaur is the durable dog toy of your pup’s prehistoric dreams! Donny includes a loud Grunter and features plaid accents, embroidered detailing and colorful cross-stitched fabric. Constructed using ZippyPaws’ exclusive Z-Stitch® webbing and multi-layered fabric, Donny is perfect for cuddling, tossing, fetching – and chewing! However Donny is not in-destructible tho!"
            ,"NomNomz® are your favourite foods, now in plush form for your pups! Feed your dog's inner foodie with these \"delicious\" yummy treats, one sip and they'll be in doggie heaven."
            ,"Where’s Dodo?! Dodo the Dodo Bird is flightless and fearless – the perfect combo for playtime with your pupper! Dodo includes a loud Grunter and features plaid accents, embroidered detailing and colorful cross-stitched fabric. Constructed using ZippyPaws’ exclusive Z-Stitch® webbing and multi-layered fabric, Dodo is perfect for cuddling, tossing, fetching – and chewing!"
            ,"Dogs of all ages and sizes will love to get a bite of the Bolt Bite chew toy. With a reinforced centre, two elbows for engaging paw-play, and open ends for hiding treats. Whether you have a strong-jawed dog or a teething puppy, the Bolt Bite is made for all shapes, sizes and ages."
            ,"The Twist Toss is the ultimate fetch toy for dogs. It bounces unpredictably for active play and holds treats. Head to the park and have a ball or add your favourite spread and freeze the Twist Toss for a longer lasting snack."
            ,"The Triangle Tug boasts two shapes, two textures, and is perfect for tug-of-war. If you’re in a multi-dog household or if you’re at the other end of your pups tug-match, the Triangle Tug is built for you."
            ,"Keep meal time and treats exciting with the Snack Snake! Fill the opening with food or treats and let them go for gold."
            ,"This award-winning treat toy is safe for every pet as it's durable and designed to be filled with a dog's favourite kibble, wet food or treats! Toppl's soft, rounded inner 'teeth' contain a contoured cavity to hold treats in place until your dog nudges them out."
            ,"NomNomz® are your favorite foods, now in plush form for your pups! Feed your dog's inner foodie with these \"delicious\" yummy treats, one bite and they'll be in doggie heaven."
    };

     String[] accessorDescr = {"Phone rings and you’re holding your dog and a coffee? No problem. One CLIC ties your dog to a railing and so you can get to your phone. Paying for a coffee? One simple CLIC frees your hands for any occasion and errands. Stylish and innovative design for everyday use. Beige colour rope with tan leather trim design. Perfect for any dog size up to 40kg. Tether a dog with one hand in a single motion. Option to not use a traditional collar - thanks to Leader System.\n" + "Product Measurements: 1.4m maximum in length, 8mm thickness: 8kg maximum dog weight, 11mm thickness: 40kg maximum dog weight"
            ,"If you and your furry friend like to traverse off-road, then this is the multi-purpose leash for you! The durable and flexible soft coated webbing material makes this lead waterproof, stain-proof and stink-proof, so it’s super easy to keep clean. This versatile leash allows you to go completely hands-free with cross-body functionality. You can also conveniently adjust its length from short (100cm) to long (180cm), depending on the terrain or your doggo. The adjustable length means you can even tether your doggo to a tree while you’re out exploring together. Two width to choose from 2cm (Small) or 2.5cm (Large)."
            ,"If you and your furry friend like to traverse off-road, then this is the multi-purpose leash for you! The durable and flexible soft coated webbing material makes this lead waterproof, stain-proof and stink-proof, so it’s super easy to keep clean. This versatile leash allows you to go completely hands-free with cross-body functionality. You can also conveniently adjust its length from short (100cm) to long (180cm), depending on the terrain or your doggo. The adjustable length means you can even tether your doggo to a tree while you’re out exploring together. Two width to choose from 2cm (Small) or 2.5cm (Large)."
            ,"This simple leash is a perfect multi-tasker for everyday use! Use it in different ways with adjustable lengths. Strong and easy to use buckle, make everyday dog walk activities enjoyable!"
            ,"This simple leash is a perfect multi-tasker for everyday use! Use it in different ways with adjustable lengths. Strong and easy to use buckle, make everyday dog walk activities enjoyable!"
            ,"This simple leash is a perfect multi-tasker for everyday use! Use it in different ways with adjustable lengths. Strong and easy to use buckle, make everyday dog walk activities enjoyable!"
            ,"Our all weather collars are a durable alternative to leather. They are made with sustainable recycled canvas and solid brass, for pups who love to explore. Made by hand in Australia. Canvas exterior - made from recycled plastic bottles. Synthetic core for strength - made from recycled plastic bottles. Environmental friendly. Cruelty-free. Sewn and hand riveted. Solid brass hardware."
            ,"Looking for something that's back-to-school-chic? Tartan is a classic style so we've made these from a left over roll of school uniform twill. The colours look smart with brass hardware for a slightly formal look. Is 'dapper' your middle name? Then this is for you. Environmental friendly. Made by hand in Australia. Cotton exterior for beauty. Synthetic core for strength. Sewn and hand riveted. 100% solid brass hardware."
            ,"Each Le Classic Dog Collar is a chic and ultra-comfortable essential for the on-the-go dog. Every vibrant collar is made of premium-quality vegan materials + faux leather. Le Classic Collar comes in four sizes for the perfect fit and was created to suit dogs of all temperaments. Collars features a matte black buckle + triangle ring, antique gold eyelets and our custom rose emblem. We truly believe that luxury lies in the delicate details. Each Le Classic Dog Collar and its striking pattern can be paired with a matching Le Classic Leash to complete the signature look."
            ,"No more rashes under your armpits! Hooray to the patented smart design of X-Harness, make running around in parks or beaches extra fun! Made from strong acrylic yarn with the feel of cotton's soft texture. One continuous strap. Easy to put on and remove without pulling your dog’s legs through the harness."
            ,"No more rashes under your armpits! Hooray to the patented smart design of X-Harness, make running around in parks or beaches extra fun! Made from strong acrylic yarn with the feel of cotton's soft texture. One continuous strap. Easy to put on and remove without pulling your dog’s legs through the harness."
            ,"No more rashes under your armpits! Hooray to the patented smart design of X-Harness, make running around in parks or beaches extra fun! Made from strong acrylic yarn with the feel of cotton's soft texture. One continuous strap. Easy to put on and remove without pulling your dog’s legs through the harness."
    };

     String[] groomDescr = {"Super handy Andis Blade Cleaning Brush with nice long bristles. Designed specifically for cleaning blades and clippers. Measures 14cm total length. The bristle area of the brush measures 6cm and the bristles themselves are a generous 1.5cm long for really getting out stuck fur. Great for brushing out fur from between blade teeth and between blades, cleaning clipper parts like the blade latch and air filter - a great little all-rounder!"
            , "Natural Wooden Bamboo Bristle Brush Single Sided. Medium/Firm Bristles. Bristles Length 2 cm. Total Brush Length 22 x 6 cm. Ideal time saver."
            , "Very sturdy rubber brush. Can be used on Dogs or Horses. Treat your Dog  or Horse to a safe gentle massage. Great for massaging in shampoo. Lots of soft rubber pins for a gentle massage. Easy to hold fits nicely in your hand with good grip. Weight: 0.2 kg."
            , "High quality steel. These are a great scissor for the entry level Groomer  up to the  intermediate level Groomer. Thinners are 6.5″. Straight Scissor & Curved Scissor are 7″. Available in Electric Blue only. This Triple Pack comes with its own pouch for convenience & safety."
            , "The Black Pearl is a shear designed to revolutionize the industry. Very high quality at low cost. Designed with our ergonomic shank handle design, this shear has power, but can handle the smallest details with finesse. Weight: 1 kg."
            , "Tooth to Tooth measures 3.5cm. Stripping tools are ideal for removing loose hair and thin out undercoats quickly and easily. Special designed curved blades with rounded ends for safety. Comfortable wooden handle is easy to grip, reduces  hand fatigue. Strips coats cleanly and effectively, leaving coats and skin healthy. For best result, and to avoid removing excessive top coats, use only in the direction of hair growth. 8 Blade, 10 Blade, and 12 Blade for prep work and thinning. 13 Blade, 16 Blade, and 20 Blade for heavy coats. 26 Blade, 27 Blade, and 32 Blade for finishing or on thick, shaggy coats. Weight: 1 kg."
            , "Unique de matting tool has double sided stainless steel blades. Fine on one side and Coarse on other to remove mats, tangles and knots easily without losing coat length. 9 Blades on the Coarse side. 17 Blades on the Fine side. Easy grip rubber handle. Weight: 0.1 kg."
            , "Running Time of  240 mins – 4 hours on low speed, 180 min at high speed. Re-Charge in ONLY 60 mins. Convenient Battery Level Indicator for ease of use. RED LIGHT -FLAT CHARGING. ORANGE LIGHT TRICKLE CHARGING. GREEN FULLY CHARGED. PLEASE NOTE:BATTERY MUST BE COLD BEFORE PLACING ON THE CHARGER UNIT THIS WILL PROLONG THE LIFE OF THE BATTERY. Lightweight & Economical Design to fit perfectly in the hand. Ideal for all Dog Types & Full Body Clips on Horses. Weight: 5 kg."
            , "Professional Grooming Clipper. Ergonomically designed  – light weight at 350gm. Slim styling – Slip resistant grip on lower case for secure hold and improved handling. Two powerful speeds  3000 and 3700 rpm. Brushless motor. 4.2 metre long cord. Energy saving switch mode power supply with low voltage, greater safety for user and animal. Fast cutting size 10 blade with cutting length of 1.8mm. Bottle of Blade Oil."
            , "Excellent Small Clipper for Full Clips on Cats and Dogs. Bridle Paths on Horses. Touch up for Freeze Branding. This Clipper has a quiet and powerful 35w permanent magnet motor. Handpiece and battery weigh only 440gms. Weight: 2 kg."
            , "Great for Cats and Dogs. Ideal for brush-outs and mat removal. Leaves coats smooth looking. Head has angled pins are great for detangling with the least risk of brush burn. Ideal for bath prepping or undercoat removal. Brush Head measures  6cm x 4cm. Easy grip rubber handle. Weight: 0.1 kg."
            , "Removes mats, dead and shedding hair with great results with no extra effort. Brush features a super strong soft plastic grip handle Soft foam-cushioned pad and curved head. Removes shedding hair without damaging topcoat Soft foam-cushioned pad and curved head. Soft foam-cushioned pad and curved head. Provides a beautiful and long lasting well groomed finish. Easy grip rubber handle for ease of use. Large Size measures 12cm x 7cm. Weight: 0.1 kg"
    };

    public Categories(InputStream filepath){
        this.filepath = filepath;
    }


    public ArrayList<Item> generateItemData(String whichCategory){
        ArrayList<Item> itemsArray = new ArrayList<Item>();
        String[] descriptArray;
        // To choose which category should be used to get the corresponding descriptions
        if (whichCategory.equals("Foods")){
             descriptArray = foodDescr;
        } else if(whichCategory.equals("Toys")){
            descriptArray =  toysDescr;

        }else if(whichCategory.equals("Accessories")){
            descriptArray = accessorDescr;

        }else{
            descriptArray = groomDescr;
        }
        String line = "";
        String splitBy = ",";
        int  i = 0;
        try {
            // Extracting data from csv
            BufferedReader br = new BufferedReader(new InputStreamReader(filepath, Charset.forName("UTF-8")));
            while ((line = br.readLine()) != null)
            {
                String[] items = line.split(splitBy);

                String itemName = items[1];
                String itemImgPaths =  items[0];
                String itemPrice = items[2];
                String itemDescription = descriptArray[i];
                Item anItem = new Item(itemName,itemPrice,itemDescription,itemImgPaths);
                itemsArray.add(anItem);
                i++;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("Finished generating data");
        return itemsArray;
    }



}

